- name: Exe
  # You may pin to the exact commit or the version.
  # uses: lando/pkg-action@0d0a00d1f6c893ed81cf326a5a869e3a5da358ae
  uses: lando/pkg-action@v2
  with:
    # The binary entrypoint path
    entrypoint: dist/index.js
    # The architecture to build for x64|amd64|aarch64|arm64
    arch: x64
    # The node version to package with
    node-version: node16
    # The operating system to build for win|linux|macos
    os: win
