name: Create exe file

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  exe:
    runs-on: windows-latest
    
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
      with:
        node-version: 19.1.0
    
    - name: Build exe
      run: npm i && npm run exe
    
    - name: Create Release
      uses: ncipollo/release-action@v1.11.2
      with:
        bodyFile: exe/credr-terminal.exe
        generateReleaseNotes: true
      
