name: Create exe file

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  exe:
    runs-on: windows-latest
    
    steps:
      

    
    - name: Build exe
      run: ls -a
    
