name: Create exe file

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  exe:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19.1.0
    
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run exe
      
    - name: List
      run: ls exe
