name: Release exe file

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  exe:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 19.1.0
    
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run exe
      
    - name: Release
      uses: djnicholson/release-action@v2.10
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        asset-name: Credr Terminal
        file: exe/credr-terminal.exe
